version: 2
formats: all

build:
  os: ubuntu-22.04


python:
  version: 3.8
  install:
    - requirements: docs/rtd-requirements.txt
    - requirements: docs/requirements.txt

  system_packages: true
