version: 2
formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"


python:
  install:
    - requirements: docs/rtd-requirements.txt
    - requirements: docs/requirements.txt

  system_packages: true
